### PR TITLE
Converter support

### PR DESCRIPTION
**Pull request by trdsolutions**
I find it quite useful to have the ability to use the TranslateExtension with an IValueConverter.
Hopefully you see this also as an improvement to your great library.

### CODE REVIEW

**Comment by SirJohnK** [comment]
Hi, @trdsolutions! 😃 

Thanks for the effort of contributing! 👍 
- Yes, I have also been thinking of adding IValueConverter to TranslateExtension, but have not found any good use case.
- Most use cases could be solved with the TranslateBindingExtension and/or the TextTransform property on Label, Button etc.
- Can we come up with any other use case that is useful regardless of the current culture/language?

/Regards Johan

**Comment by trdsolutions** [comment]
@SirJohnK 

Thanks for pointing me out to the `TextTransform` property. I was not aware of this, as I just started going deepter into MAUI, while I'm mostly working with WPF, where I use the same localization approach (including the converter support).

With this ability, I actually don't have a use-case anymore in my mind. I will check my WPF solutions on monday, to see, if there was any other usage of this, but if not, I will revoke the PR.

Thanks and best regards,

Tobi

**Comment by trdsolutions** [comment]
@SirJohnK 

Sorry for my late response.
I did not found any other use cases for this and will close this.

Thanks for your support and your great work on this library!

**Comment by SirJohnK** [comment]
@trdsolutions , thank you!

Look out for v1.3.0 coming soon with some really useful additions! 😃

**Pull request closed without merging**
